# Generated by Django 4.1.3 on 2022-11-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='publisher_name',
            field=models.CharField(default='maskedman', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cell',
            name='comment_text',
            field=models.TextField(default='maskedman', max_length=200),
        ),
        migrations.AddField(
            model_name='cell',
            name='theme',
            field=models.ForeignKey(default='theme', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='comments.theme'),
            preserve_default=False,
        ),
    ]
