# Generated by Django 4.1.3 on 2022-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_theme_cell_publisher_name_alter_cell_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='comment_text',
            field=models.TextField(max_length=200),
        ),
    ]
